"""add insurance plans and simplify insurance policy

Revision ID: 3d81d7427995
Revises: d983ba2e18a4
Create Date: 2026-10-03 20:47:18.513301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d81d7427995'
down_revision: Union[str, Sequence[str], None] = 'd983ba2e18a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_policies', sa.Column('plan_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('insurance_policies_couple_id_fkey'), 'insurance_policies', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_policies', 'couples', ['couple_id'], ['id'])
    op.create_foreign_key(None, 'insurance_policies', 'insurance_plans', ['plan_id'], ['id'])
    op.drop_column('insurance_policies', 'policy_name')
    op.drop_column('insurance_policies', 'duration_months')
    op.drop_column('insurance_policies', 'monthly_premium')
    op.drop_column('insurance_policies', 'policy_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_policies', sa.Column('policy_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('insurance_policies', sa.Column('monthly_premium', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('insurance_policies', sa.Column('duration_months', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('insurance_policies', sa.Column('policy_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'insurance_policies', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'insurance_policies', type_='foreignkey')
    op.create_foreign_key(op.f('insurance_policies_couple_id_fkey'), 'insurance_policies', 'couples', ['couple_id'], ['id'], ondelete='CASCADE')
    op.drop_column('insurance_policies', 'plan_id')
    # ### end Alembic commands ###
