"""initial migration

Revision ID: 4f2d82b7a5dd
Revises: 
Create Date: 2026-09-30 19:44:14.275574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2d82b7a5dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('users_couple_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_couple_id_fkey'), 'users', 'couples', ['couple_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
